extends: [[spectral:oas, recommended]]

rules:
  operation-operationId: error
  operation-tags: error
  oas3-api-servers: error
  info-contact: warn
  info-license: warn
  no-eval-in-markdown: error
  no-script-tags-in-markdown: error
  operation-description: warn
  operation-success-response: error
