extends: [[spectral:oas, recommended]]

rules:
  operation-operationId:
    severity: error
  operation-tags:
    severity: error
  oas3-api-servers:
    severity: error
  info-contact:
    severity: warn
  info-license:
    severity: warn
  no-eval-in-markdown:
    severity: error
  no-script-tags-in-markdown:
    severity: error
  operation-description:
    severity: warn
  operation-success-response:
    severity: error
